### PR TITLE
Declare kitchen-inspec to be run serially

### LINKED ISSUE #167: Inspec-1.51.* fail with --concurrency option in kitchen
Hello,

I just found out a bug and I am not sure if the issue is within kitchen-inspec or inspec itself.
When I use --concurrency option while doing kitchen verify I get the following error:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [undefined method `each' for nil:NilClass] on test-cookbook-centos-7-x86-64
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

If I remove the --concurrency option the kitchen verify finishes without issue.
I got the same result on two dinstinct servers and even on my workstation.

Here are the version I tried:
- kitchen-inspec: 0.22.0, 0.20.0
- inspec: 1.51.*

It works with inspec-1.49.2 though.

I could not test it with inspec-2.* because I have the following issue, even though I have inspec-2.0.17 installed. Should I open another issue about that or is it an issue on my end only ?
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'inspec' verifier from the load path. Please ensure that your transport is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Let me know if you need any more informations

Thanks

### PR DESCRIPTION
**Pull request by clintoncwolfe**
### Description

Informs test-kitchen that the `inspec` verifier should not be run multithreaded.  This is because Chef InSpec is not thread-safe, due to RSpec not being thread safe; when run multithreaded, random test failures or test count inaccuracies can occur, as well as random `No method each for nil::NilClass` errors. See #167 and https://github.com/test-kitchen/test-kitchen/issues/1530 for details.

~PR set as draft until https://github.com/test-kitchen/test-kitchen/pull/1678 merges and the TK version is bumped, because this needs to have an updated version pin against test-kitchen in the kitchen-inspec gemspec.~ TK 2.7.0 includes the feature.

### Issues Resolved

Closes #167

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by tas50** [comment]
This either needs a if responds wrapping or the kitchen dep bumped to 2.7
